FROM gradle:6.7.1-jdk11-openj9 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon

FROM arm32v7/adoptopenjdk:11-jre-hotspot
COPY qemu-arm-static /usr/bin/
ARG JAR_FILE=build/libs/*.jar
RUN mkdir -p app/data
COPY --from=build /home/gradle/src/build/libs/*.jar /app/app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]