# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11.0.3-jdk-stretch
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      # Build the project and save the jar in the build workspace to be used later if needed.
      - run: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/SwanCloudServer-0.0.1-SNAPSHOT.jar

      # Store the Gradle wrapper and dependencies in order to speed things up for next time.
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      # store_test_results uploads the JUnit test metadata from the build/test-results/test directory
      # so that it can show up in the CircleCI dashboard. We also upload the test metadata as artifacts via the store_artifacts
      # in case there is a need to examine them.
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always

      # Build and publish docker images
      - setup_remote_docker:
          version: 19.03.13

      - run: |
          scp -r build/libs/SwanCloudServer-0.0.1-SNAPSHOT.jar remote-docker:build/libs/SwanCloudServer-0.0.1-SNAPSHOT.jar

      - run: |
          TAG=circleci-test
          docker build -t swancloudserver:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push swancloudserver:$TAG

#  build_arm:
#    machine:
#      image: ubuntu-2004:202101-01
#    resource_class: arm.medium
#
#    working_directory: ~/repo
#
#      environment:
#        _JAVA_OPTIONS: "-Xmx3g"
#
#    steps:



workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: DOCKER_HUB